name: benji
description: Benji user app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  http:
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  csc_picker: ^0.2.7
  google_fonts:
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^9.0.2
  geocoding:
  permission_handler: ^10.3.0
  flutter_pw_validator: ^1.6.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.1
  url_launcher: ^6.1.12
  liquid_pull_to_refresh: ^3.0.1
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  lottie:
  get: ^4.6.5
  intl:
  flutter_layout_grid: ^2.0.4
  dotted_border:
  shimmer: ^3.0.0
  readmore: ^2.2.0
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  flutter_carousel_widget:
  flutter_polyline_points:
  autoscale_tabbarview: ^1.0.2
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  plugin_platform_interface:
  pdf: ^3.10.4
  flutter_monnify: ^0.0.3
  http_parser: ^4.0.2
  agora_uikit:
  carousel_slider: ^4.2.1
  awesome_notifications:
  awesome_notifications_core:
  awesome_notifications_fcm:
  animated_switch:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/splash_screen/frame_1.png
  color: "#f9f9f9"
  image_dark: assets/images/splash_screen/frame_1.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/
    - assets/images/vendors/
    - assets/images/splash_screen/
    - assets/images/onboarding_screen/
    - assets/images/vendors/
    - assets/icons/
    - assets/images/rider/
    - assets/images/profile/
    - assets/images/products/
    - assets/images/customers/
    - assets/animations/login/
    - assets/animations/signup/
    - assets/animations/payment/
    - assets/animations/no_internet/
    - assets/animations/error/
    - assets/animations/empty/
    - assets/animations/credit_card/
    - assets/animations/delivery/
    - assets/animations/google_maps/
    - assets/frontend/assets/brand/
    - assets/frontend/assets/hero/
    - assets/frontend/assets/blog/
    - assets/frontend/assets/banner/
    - assets/frontend/assets/circle_card/
    - assets/frontend/assets/device/
    - assets/frontend/assets/footer/
    - assets/frontend/assets/mid_paragraph/
    - assets/frontend/assets/paragraph_bg/
    - assets/frontend/assets/product/
    - assets/frontend/assets/product_asset/
    - assets/frontend/assets/store/
    - assets/frontend/assets/sale/
    - assets/frontend/assets/login/
    - assets/frontend/assets/team/
    - assets/frontend/assets/error/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
